version: "3"

services:
  go:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
     - ../:/workspace
    tty: true
    stdin_open: true
    working_dir: /workspace
    environment:
      TZ: Asia/Tokyo
    ports:
      - "8080:8080"
